### ISSUE TITLE
PACKAGE IS REMOVED FROM NPM

### ISSUE THREAD

**Issue by voronianski** [npm-dom/iframe#9]
https://www.npmjs.com/package/iframe

Probably it's related to the [Azer](https://github.com/azer)'s decision as he is one of maintainers of this module.

I ask you to publish it to npm again or I will do it myself (I have an app that relies on it).

**Comment by TehShrike** [comment]
I asked for the ability to publish this module under the same name, but npm is still working through all those requests I think.  I would recommend switching to the git repo as a dependency until then.

**Comment by voronianski** [comment]
@TehShrike thanks, I've already switched. Btw all modules under "npm-dom" organisation are remove :(
